### ISSUE TITLE
permissions root issues

### ISSUE THREAD

**Issue by ghost** [Kalebu/Website-blocker-python#2]
your script assuems all acces but as linux i woudl ask to add sudo enable asa norma does nt have etc folder permission to modifu hsts so your expected result ends failing wth a permsioon diened

**Comment by ghost** [comment]
I am working on a fix but can you add automatic sudo automation

**Comment by syedjafer** [comment]
@ghost you can use `chmod -R 777 <file.py>` to avoid sudo.

**Comment by syedjafer** [comment]
I think this issue could be closed.
